# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZQRichTableExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZQRichTableExample
  pod 'TZImagePickerController','1.9.5'
  
  target 'ZQRichTableExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZQRichTableExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
